# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDEAD9
background         #15161B
cursor             #838083

active_tab_foreground     #15161B
active_tab_background     #FDEAD9
inactive_tab_foreground   #FDEAD9
inactive_tab_background   #15161B

active_border_color   #FDEAD9
inactive_border_color #15161B
bell_border_color     #061022

color0      #3C3D42
color1		#061022
color2		#061022
color3		#174A5F
color4		#438088
color5		#92797A
color6		#BB926E
color7		#F4D8C0
color8		#AB9786
color9		#08162D
color10		#08162D
color11		#1E627E
color12		#5AABB6
color13		#C2A2A3
color14		#FAC292
color15		#F4D8C0
