# uosc controls
m script-binding uosc/menu
s script-binding uosc/subtitles
a script-binding uosc/audio
v script-binding uosc/video
p script-binding uosc/playlist
c script-binding uosc/chapters
f cycle fullscreen
space cycle pause
l cycle loop-file
