vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe

profile=fast

# FAST network start
cache=yes
cache-secs=2
demuxer-readahead-secs=1
demuxer-max-bytes=20M
demuxer-max-back-bytes=5M

# YouTube format priority
ytdl-format=bv*[height<=720][vcodec!=av01]+ba/b[height<=720]
