# Video
vo=gpu
hwdec=auto-safe
profile=fast

# UI (required for uosc)
osc=no
osd-bar=no
border=no

# Volume & Persistence
save-position-on-quit=yes
watch-later-options=volume
volume=100
volume-max=200

# Ease of Use
keep-open=yes
cursor-autohide=1000
